name: "Build and publish container"

# on:
#   workflow_run:
#     workflows: ["Bump version and tag"]
#     branches: [main]
#     types:
#       - completed

on:
  push:
    branches: "**"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker build and push
        run: |
          tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          docker build -t smetj/xpectd:latest .
          docker tag smetj/xpectd:latest smetj/xpectd:$tag
          docker push smetj/xpectd:latest
          docker push smetj/xpectd:$tag
