name: "Run Tests"

on:
  pull_request:
    branches:
      - main

jobs:
  run-pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install package
        run: |
          python setup.py install
          pip install -e .[test]
      - name: Run tests
        run: python setup.py test
